apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: gp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
        - name: log-generator
          image: busybox
          args:
            - /bin/sh
            - -c
            - |
              mkdir -p /logs/myapp;
              while true; do
                echo "$(date) - INFO - app-log Writing another log pattern $(shuf -i 1000-2000 -n 1)" >> /logs/myapp/app.log;
                echo "$(date) - ERROR - app-log Critical issue occurred $(shuf -i 5000-6000 -n 1)" >> /logs/myapp/app.log;
                sleep 2;
                echo "$(date) - INFO - Console log Writing another log pattern $(shuf -i 1000-2000 -n 1)";
                echo "$(date) - ERROR - Console log Something went wrong $(shuf -i 1-1000 -n 1)" >&2;
                sleep 1; 
              done
          volumeMounts:
            - name: logs-volume
              mountPath: /logs
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: logs-volume
          emptyDir: {}
